### ISSUE TITLE
Getting error when your are comparing freq(i) 

### ISSUE THREAD

**Issue by aniket-kes** [nikita9604/Piano-Note-Recognition#1]
i tried to run this code but facing one issue that is unrecognized variable.

`if ((freq(i) > 20) && (freq(i) < 20000))`

getting this error
![image](https://github.com/nikita9604/Piano-Note-Recognition/assets/99314074/a4d80cf7-c530-4cf4-aab2-2fee6e357739)

The code runs but after calculating I value 2-3 times it gets crashed with error mentioned in the above image.
Also i am passing piano audio which have 4 notes one after another in a single audio file call `piano_notes.mp3`

Tell me how to make this code run.

Also if possible can you push the audio file in this repository.

**Comment by nikita9604** [comment]
Thank you for reaching out and providing details about the error you're encountering. It's important to note that the project was originally tested for single-note recognition. Given this constraint, there might be challenges in handling cases where multiple notes are present in a single audio file with gaps between them. To address this issue, we may need to enhance the functionality of the code to handle multiple notes or gaps between notes more effectively.

As for pushing the audio file to the repository, I'll ensure the audio files are included in this repository.

If you have any further insights or suggestions on how to improve the project's capabilities in handling multiple notes, please feel free to fork and share them. Your input is invaluable in refining the functionality of my project. Thank you for bringing this to my attention!

Since this issue has remained unresolved for six months, I'll go ahead and close it. Should you encounter similar difficulties in the future or if this problem persists, please don't hesitate to create a new issue. Rest assured, I'll be vigilant in monitoring new issues and will respond promptly to address any concerns you may have. Thank you for your cooperation!
